version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app #adds host directory to container directory
    environment:
      FLASK_ENV: development #tells flask to reload the code on change